### ISSUE TITLE
phpBB 3: Specified key was too long

### ISSUE THREAD

**Issue by habakuk007** [vanilla/porter#109]
I get this error if I try porter on phpBB 3.0.12:

```
create index z_idx_pmgroup on z_pmgroup (subject, userids);Specified key was too long; max key  length is 1000 bytes

Error: (1024) Specified key was too long; max key length is 1000 bytes 
```

Any idea how to fix this?

Regards!
   Stefan

**Comment by DaazKu** [comment]
You may try this:

search for this line
``$ex->query("create index z_idx_pmgroup on z_pmgroup (subject, userids);");``

and replace it by this one
``$ex->query("create index z_idx_pmgroup on z_pmgroup (subject(100), userids(100));");``

I'm not 100% sure it will work though

**Comment by habakuk007** [comment]
Thanks!

I changed two lines (did someone say DRY?) and then it worked.

**Comment by DaazKu** [comment]
This error may or may not occur depending on the mysql configurations. There is a small risk of collision if we limit the index's fields at 100 characters each. I propose that we do not update the code and document the problem in the package.

**Comment by linc** [comment]
Here also: https://vanillaforums.org/discussion/31026/export-error

**Comment by topcheese13** [comment]
I know @DaazKu suggested we do not update the code in his comment above, is this still our opinion on this ?

MyISAM's limit is 1000 bytes, InnoDB's is 767 bytes.

We could simply replace

```
$ex->query("
    create table z_pmgroup(
    groupid int unsigned,
    subject varchar(255),
    userids varchar(250)
     );
");
```

By this

```
$ex->query("
    create table z_pmgroup(
    groupid int unsigned,
    subject varchar(191),
    userids varchar(191)
     );
");
```
And keep the index as it is

```
$ex->query("create index z_idx_pmgroup on z_pmgroup (subject, userids);");
```

**Comment by topcheese13** [comment]
After reviewing this issue thoroughly, the conclusion is to completely change how we handle the private messages from phpbb, phpbb currently works in a way that you can send 1 message to multiple users but it is treated as single messages being sent to every one of the recipients the user as selected. Which means there are no group conversation. We currently try to create group conversations by grouping together messages by participants and subjects.

```
$ex->query("
            update z_pm pm
                join z_pmgroup g on pm.subject2 = g.subject
                    and pm.userids = g.userids
            set pm.groupid = g.groupid;
        ");
```
I believe the downside of this outweighs the upside. Upside is, when people come over Vanilla their previous private messages have the same "feel" than the new ones they will create but we might be grouping together conversations that shouldn't be. For example I could send to the same people multiple new conversations with the subject "Hi" they would end up being grouped together and they shouldn't be. We could be grouping conversations from 10 years ago with a new one from a week ago.

I believe we could be handling the private messages this way

```
// Conversations.
        $conversation_Map = array(
            'RealSubject' => array(
                'Column' => 'Subject',
                'Type' => 'varchar(250)',
                'Filter' => array('Phpbb2', 'EntityDecode')
            )
        );
        $ex->exportTable('Conversation', "
            select
                pm.message_subject as RealSubject,
                pm.msg_id as ConversationID,
                pm.author_id as InsertUserID,
                from_unixtime(pm.message_time) as DateInserted
            from :_privmsgs pm
            where root_level = 0
        ", $conversation_Map);

        // Coversation Messages.
        $conversationMessage_Map = array(
            'message_text' => array('Column' => 'Body', 'Filter' => array($this, 'removeBBCodeUIDs')),
        );
        $ex->exportTable('ConversationMessage', "
            select
                pm.msg_id as MessageID,
                if(root_level = 0, msg_id, root_level) as ConversationID,
                pm.author_id as InsertUserID,
                pm.message_text,
                pm.bbcode_uid,
                'BBCode' as Format,
                FROM_UNIXTIME(pm.message_time) as DateInserted
            from :_privmsgs pm
        ", $conversationMessage_Map);
        
        // User Conversations.
        $ex->exportTable('UserConversation', "
            select distinct
                mt.msg_id as ConversationID,
                mt.user_id as UserID
            from
                phpbb_privmsgs_to mt
            join
                phpbb_privmsgs m on m.msg_id = mt.msg_id and m.root_level = 0
        ");
```

Instead of doing it this way:

https://github.com/vanilla/porter/blob/master/packages/phpbb3.php#L297


Recap
---
We would now migrate private messages has they really are, 1 to 1 messages in every case.
This would prevent possibly grouping together content that shouldn't be, and I believe will bring over a more accurate content on Vanilla of what was the content on phpbb. Only downside is there will be a disparity in how group conversations work on Vanilla between the migrated data and the new created messages.

@DaazKu @initvector if you could let me know if you agree with the above. Thanks.

**Comment by DaazKu** [comment]
Sounds good to me.

**Comment by initvector** [comment]
Would it be difficult to allow this as an option? The current migration into Conversations is nice, but it can obviously cause some issues for imports. Maybe the package should convert conversations by default, but also allow users to avoid converting conversations (thus keeping the old phpBB message structure), if they run into these index errors.

**Comment by topcheese13** [comment]
Problem is, grouping the wrong things together and the index errors aren't related, I'd rather have a 100% accurate representation of their PMs than a nicer one where some messages are grouped together when they shouldn't be.

**Comment by topcheese13** [comment]
After talking to @initvector we would implement the new logic (excluding grouping as an option).

This way the user gets to choose and we have an alternative when the package crashes because of the length of some values in the index.
