### ISSUE TITLE
Windows line breaks

### ISSUE THREAD

**Issue by linc** [vanilla/porter#15]
https://github.com/vanillaforums/Garden/issues/1351

**Comment by initvector** [comment]
*This issue is two years old, so this may no longer be a problem.*

Export entries written with ExportModel::WriteRow are forcing line endings to be line feed (LF), only, not carriage return (CR) + line feed (LF).  Existing CR+LF are replaced in strings before being written.  Rows are explicitly terminated with ExportModel::NEWLINE, which is defined as LF.

When the import process is run, the LINES TERMINATED BY parameter of LOAD DATA INFILE is explicitly set to LF.  This should maintain cross-platform compatibility, since we're normalizing line endings to LF, regardless of platform.

Can this issue be confirmed using a current version of Porter and Vanilla on Windows?

**Comment by Daazku** [comment]
The line endings are correct and appropriate for an export file format.
If anyone run into similar problem they should create a new issue about it.
