### ISSUE TITLE
Error trying to export from Kunena

### ISSUE THREAD

**Issue by kbrookes** [vanilla/porter#191]
Hi there,

I'm currently trying to export from Kunena Forum v5.1.15

Getting the following error:

`         SELECT
            u.*,
            case when ku.avatar <> '' then concat('kunena/avatars/', ku.avatar) else null end as `Photo`,
            case u.usertype when 'superadministrator' then 1 else 0 end as admin,
            coalesce(ku.banned, 0) as banned,
            ku.birthdate,
            !ku.hideemail as showemail
         FROM btqhl_users u
         left join btqhl_kunena_users ku
            on ku.userid = u.id;Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'u.usertype' in 'field list'
)
         select t.*, 1 as Bookmarked
         from btqhl_kunena_subscriptions t;Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'vxqrugsyxe.btqhl_kunena_subscriptions' doesn't exist
)
Error in webroot/vanilla2export.php line 1190: (2) urldecode() expects exactly 1 parameter, 4 given`

Any help would be appreciated!

**Comment by patches** [comment]
Hi @kbrookes,

From the error message you got above, it seems like the database structure is different than the one this package was used on. There might be a few reasons for that since this package was created a few years ago.

## First error

```sql
SELECT u.*, case when ku.avatar <> '' then concat('kunena/avatars/', ku.avatar) else null end asPhoto, case u.usertype when 'superadministrator' then 1 else 0 end as admin, coalesce(ku.banned, 0) as banned, ku.birthdate, !ku.hideemail as showemail FROM btqhl_users u left join btqhl_kunena_users ku on ku.userid = u.id;
```
```
Array (
    [0] => 42S22 
    [1] => 1054 
    [2] => Unknown column 'u.usertype' in 'field list'
)
```

The `btqhl_users` table in your database doesn't have the a `usertype` column. This column is used in the package to determine which users are administrators. The easiest solution would be to manually add this column to your database, even if it is null for each users.

## Second error

The second error is due to the fact that your database doesn't have a `kunena_subscriptions` table. It seems like this table was originally used to store user bookmarks (starred threads).

```sql
select t.*, 1 as Bookmarked from btqhl_kunena_subscriptions t;
```
```
Array (
    [0] => 42S02 
    [1] => 1146 
    [2] => Table 'vxqrugsyxe.btqhl_kunena_subscriptions' doesn't exist 
)
```

The `kunena_subscriptions` table has 2 columns:
- thread
- userid

You can manually add this table (with the two columns above) in your database to prevent the error from showing.

## Third error

```
Error in webroot/vanilla2export.php line 1190: (2) urldecode() expects exactly 1 parameter, 4 given
```

These are the 2 lines causing the last error.

https://github.com/vanilla/porter/blob/master/packages/kunena.php#L163
https://github.com/vanilla/porter/blob/master/packages/kunena.php#L167

Our [filter-functions.php](https://github.com/vanilla/porter/blob/master/functions/filter-functions.php) file should have a urlDecode function, but it currently doesn't. The PHP `urldecode` function is called, however it only takes 1 parameter. This should only cause a warning to be fired.

If it causes an error and prevents the execution of the porter, you can alternatively open the vanilla2export.php file and remove the `, 'Filter' => 'urlDecode'` part from the two lines I sent above. Doing so might affect the `Path` and `Filename` of the entries in your Media table after the import. You should double check the Media table after the import. 

Hope this will help you out.

**Comment by kbrookes** [comment]
Thank you - that was good advice. We got it sorted :)
