### ISSUE TITLE
Publicize the feature matrix

### ISSUE THREAD

**Issue by dandv** [vanilla/porter#59]
I've been looking around the docs for too many minutes for something that should be easily accessible:

![image](https://cloud.githubusercontent.com/assets/33569/7084541/357d1fae-df23-11e4-9059-52ea8b44eb18.png)

Had to install and run the script to get that, so I've made a [PR against the docs](https://github.com/vanilla/vanilladocs/pull/36).

**Comment by linc** [comment]
To give some background, that's a very new feature, and my concern is we have no way to automatically update it, so it's going to get obsoleted constantly. Since there's a PR to track this and it's a docs issue anyway, I'm gonna close this. Check my notes for including the image in the repo on the PR.
