### ISSUE TITLE
Improve installation instructions on the addon's home page / friendlier error message

### ISSUE THREAD

**Issue by dandv** [vanilla/porter#60]
Running the PHP script out of the box produced

> Error: (2) touch(): Unable to create file vanilla2test.txt because Permission denied

Took me a bit to realize that I have to create a directory writable by the webserver, from which to run `vanilla2export.php`. I use a VPS with nginx and have MyBB in /var/www/MyBB. Nothing unusual.

**Comment by dandv** [comment]
UPDATE: in the meantime I found the instructions to create a writable directory at http://docs.vanillaforums.com/developers/importing/porter/. Maybe it's worth putting that bit at http://vanillaforums.org/addon/porter-core, maybe not.

**Comment by initvector** [comment]
Thanks for reporting this!  This was a problem with the error handler.  It **should** have detected it couldn't create the file and then print the following error message on the index page:

*The porter does not have write permission to write to this folder. You need to give the porter permission to create files so that it can generate the export file.*

Now it should be a little easier to determine what's going on.
