### ISSUE TITLE
Please support Woltlab Burning Board

### ISSUE THREAD

**Issue by PatrickHuetter** [vanilla/porter#67]
Please support Woltlab Burning Board (e.g. wBB3 Lite and wBB3 and so on).

**Comment by linc** [comment]
This is gonna need a pull request. :) We can't just make this appear out of thin air since none of us use it. I'll give you a hint tho: Someone made one but then disappeared and didn't sign the CLA so we couldn't incorporate it https://github.com/vanilla/porter/pull/8 Maybe try poking them so we can reopen it?
