### ISSUE TITLE
IPB: "The specified data type (StorageMethod) is not accepted"

### ISSUE THREAD

**Issue by alapasset** [vanilla/porter#75]
Hello everyone,

I just try to migrate my IPB forum to Vanilla but when i try to import my exported file, I have this message :

There was an error while trying to create the Media table (The specified data type (StorageMethod) is not accepted for the MySQL database.).

Thx for your help!

**Comment by Reload3r** [comment]
I get the same error message , also importing IPB.

**Comment by garyblankenship** [comment]
The current master branch of Vanilla forum doesn't have a **StorageMethod** column in the **Media** table.  The IPB exporter MediaMap array has a StorageMethod index.  The Vanilla forum import fails because it can't map the generated data in the Media.txt file to a column in the database.

In line 6641 of **vanilla2export.php**, I'm commenting out  `// 'StorageMethod' => 'StorageMethod',` and going to run the vanilla2export.php file again to generate a new export file.

That allowed it to get past the "Define Tables" step, and the import is finished.

**Comment by Reload3r** [comment]
Thanks Gary! this fixed the issue for me.

**Comment by CA3LE** [comment]
Thanks brother!  Fixed it for me as well.
