### ISSUE TITLE
Update Porter to be PHP7-compatible

### ISSUE THREAD

**Issue by DaazKu** [vanilla/porter#95]
The porter use the mysql extension which is removed in PHP7

So PDO_MYSQL or MySQLi?

**Comment by linc** [comment]
Part of the idea of Porter is that it can the lifeboat off an old, twisted server. So removing the mysql extension in order to support PHP7 is the reverse of how to think about this: How do we not block PHP7 without sacrificing that critical legacy support? It seems like mysqli serves this purpose best because it's nearly 1:1 with mysql and has a far larger support base on legacy systems. In fact, I'd consider the possibility of switching to mysqli but leaving mysql as a fallback.

**Comment by Daazku** [comment]
I am gonna do an abstraction around the used extension then.

**Comment by cindyker** [comment]
:( I guess this hasn't finished yet.

**Comment by R-J** [comment]
Although I guess the guy from [this discussion](https://open.vanillaforums.com/discussion/33808/vanilla-porter-and-php-7-1) isn't using the porter the right way, it is now a real problem since people want to use Vanilla with PHP7

**Comment by topcheese13** [comment]
Here is the general plan I came up with after reading what was previously written.

* Create an interface (database abstraction) to standardize the functions of the database classes (https://github.com/vanilla/porter/issues/97)
* Create database classes for MYSQL and MYSQLI that will implement the interface
* Develop this keeping in mind a future PDO implementation as PDO now includes unbuffered queries
* One of the big challenge will be to implement this while keeping the amount of package refactoring as low as possible.
* Detect installed extensions to determine what database class should be used.

**Comment by topcheese13** [comment]
@initvector brought up a valid point regarding this.

The `make.php` feature. If we were to add `mysql`, `mysqli` and possibly `pdo` classes based on a class abstraction (interface), all of this would have to be included in` make.php`. Do we foresee this a being an issue ?

**Comment by linc** [comment]
What, exactly, is the concern? File size? Or something else?

**Comment by initvector** [comment]
When I brought this up to @topcheese13 it was to make sure it was considered (and tested), because it's not often a functionality we use, internally. Including a database abstraction layer is sure to increase the final file size, but I doubt it's going to be enough to warrant concern.

**Comment by R-J** [comment]
At the moment I'm trying to find a distro that I can install in a VM that has outdated enough packages so that I can use the porter. That feels really awkward!

Sure that there is a need for avoiding a pro-PDO decision? If someone is trying to switch to Vanilla he will have to have a PHP7  + MySQL installation anyway. Why not require him to export his old db and import it into the new db where PDO will be no problem?

**Comment by topcheese13** [comment]
Hey R-J,

Although I agree with what you are saying, Porter being a tool to export a legacy forum into an importable format for Vanilla. People might have their old forum running on older versions of php. It is true they could export the DB and import it on the new server running PHP7.0+ because of the requirements to run Vanilla but I feel this might be an extra stop not necessary.

Implementation of a database abstraction layer, allowing the use of the 3 extensions (mysql, mysqli and pdo) has already begun. The first "draft" of this is currently in a PR up for review.

**Comment by donovandb** [comment]
I see this issue was opened in 2015. I'm in need of Porter with PHP 7 ability now (to convert a vBullitin 5 forum) is this ready yet?

**Comment by DaazKu** [comment]
Was https://github.com/vanilla/porter/pull/154 closing this issue?

**Comment by topcheese13** [comment]
No, porter is ready to handle php 7.0+ on that feature branch https://github.com/vanilla/porter/pull/154 but packages need to be updated to replace all mysql functions before merging into master and closing this issue.
